version: "3"

services:
  wishlist-db-dev:
    container_name: wishlist-db-dev
    image: surrealdb/surrealdb:1.0.0
    env_file:
      - .env
    ports:
      - ${SURREAL_PORT}:8000
    command: start file:${SURREAL_DB_FILE}
    restart: always
    volumes:
      - ${SURREAL_DB_FILE}:${SURREAL_DB_FILE}

  wishlist-app-dev:
    container_name: wishlist-app-dev
    depends_on:
      - wishlist-db-dev
    build:
      target: builder
    env_file:
      - .env
    volumes:
      - .:/var/www/wishlist
    ports:
      - ${SERVER_PORT}:7000
    restart: always
    command: sh -c "cargo watch -x run"
