name: deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    steps:
      - name: Generating the.env file
        run: |
          cd ${{ secrets.APPDIR }}
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Updating and launching app through ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.APPDIR }}
            git checkout main
            docker compose down
            docker compose up
