name: Deploy on prod

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    steps:
      - name: Updating and launching app through ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROD_APP_DIR }}
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            git checkout main
            git pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d
            exit
